KSOURCE      = http
KSOURCE_DESC = Triggermesh HTTP Event Source for Knative
BASE_DIR    := $(CURDIR)/..

include $(BASE_DIR)/scripts/inc.Makefile

GOPKGS = ./cmd/... ./pkg/adapter/... ./pkg/apis/... ./pkg/reconciler/...

include $(BASE_DIR)/scripts/inc.Target
