# Copyright (c) 2020 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sample OciMetricsSource object.

apiVersion: sources.triggermesh.io/v1alpha1
kind: OciMetricsSource
metadata:
  name: metrics-test
spec:
  # required to interact with the Oracle Cloud API
  oracleApiPrivateKey:
    secretKeyRef:
      name: oraclecreds
      key: apiKey
  oracleApiPrivateKeyPassphrase:
    secretKeyRef:
      name: oraclecreds
      key: apiPassphrase
  oracleApiPrivateKeyFingerprint:
    secretKeyRef:
      name: oraclecreds
      key: apiKeyFingerprint
  oracleTenancy: ocid1.tenancy.oc1..aaaaaaaaswreplaceme
  oracleUser: ocid1.user.oc1..aaaaaaaaqlocaluser
  oracleRegion: us-ashburn-1

  # required to enable metrics
  metricsNamespace: oci_computeagent
  metricsQuery: CPUUtilization[1m].mean()
  # optional polling frequency. default to 5m
  #metricsPollingFrequency: 5m

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display

---

apiVersion: v1
kind: Secret
metadata:
  name: oraclecreds
type: Opaque
stringData:
  apiPassphrase: 'replace-me'
  apiKeyFingerprint: '5c:75:c4:67:92:a9:46:2a:01:5b:73:54:6a:b2:74:7d'
  apiKey: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIXEpAIBACKCAQEA2UM2O2lz4D6gN2sAbxUg6VMnGQlrwNbZX7b/wqW6ZEU0Q0BU
    ...
    -----END RSA PRIVATE KEY-----

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
